---
title: "Great Register Summary report"
author: "Rebecca Weiss"
date: "March 7, 2016"
output: pdf_document
---

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
suppressPackageStartupMessages()
library(plyr)
library(reshape)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(readr)
options(scipen=100000)
setwd('/Users/rweiss/Box Sync/CaliforniaGreatRegisters/staging_data')
```

# County statistics
```{r}
year_dates = read_csv('https://raw.githubusercontent.com/rjweiss/CaliforniaGreatRegister/master/year_dates.csv')
pop = read_csv("https://raw.githubusercontent.com/rjweiss/CaliforniaGreatRegister/master/populations.csv")
pop = melt(as.data.frame(pop), id = 'year')
pop$value = as.numeric(pop$value)
ggplot(pop, aes(x=year, y=value, fill=variable, color=variable)) + geom_line() + theme_gdocs() + scale_color_tableau() + ggtitle('Observed populations of each county by decennial census')
```

### More on counties

```{r}
alameda = read_csv('alameda_successes.txt')
sanbernardino = read_csv('sanbernardino_successes.txt')

alameda_rows = ddply(alameda, .(rollnum, pagenum), summarize, 
                     n=length(pagenum))

sanbernardino_rows = ddply(sanbernardino, .(rollnum, pagenum), summarize, 
                     n=length(pagenum))

```


## Extraction task summary
```{r}
county_stats = read.csv('county_stats.txt')
```

## Roll-level statistics
```{r, echo=FALSE}
roll_stats = read.csv('roll_stats.txt')
foo = merge(roll_stats, year_dates, by=c('county', 'rollnum'))
foo$totalpages = as.numeric(foo$totalpages)
foo$failedpages = as.numeric(foo$failedpages)
#foo$rollnum = as.numeric(foo$rollnum)
df = melt(foo, id=c('county','year', 'rollnum'))
ggplot(df, aes(x=year, y=value, fill=variable)) + geom_bar(stat='identity', position='dodge') + facet_wrap(~county) +coord_flip()
```

